server:
  port: ${APPLICATION_PORT}
  servlet:
    context-path: "/api/todoapp"

spring:  
  application:
    name: todoapp
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': ${IS_FORMAT_SQL}
    show-sql: ${IS_SHOW_SQL}
  output:
    ansi:
      enabled: ${HOW_ANSI_OUTPUT_IS_ENABLED}

  logging:
    level:
      root: INFO
      org.springframework.web: ERROR
      org.hibernate: ERROR
      com.demo.todoapi: DEBUG


